---
title: "cross_validation"
author: "Bohan Zhu"
date: "2025-11-11"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy = TRUE)
```

```{r,include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  fig.retina = 2,
  dpi = 320
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
library(tidyverse)
library(p8105.datasets)
library(modelr)

data("lidar")
```


Look at the data
```{r}
lidar_df =
  lidar |> 
  mutate(id = row_number())

lidar_df |> 
  ggplot(aes(x = range, y = logratio)) +
  geom_point()
```

## Create dataframes
```{r}
train_df = 
  sample_frac(lidar_df, size = .8) |> 
  arrange(id)

test_df = anti_join(lidar_df, train_df, by = "id")
```

Look at these
```{r}
ggplot(train_df, aes(x = range, y = logratio)) +
  geom_point()+
  geom_point(data = test_df, color = "red")
```

Fit a few models to `train_df`

```{r}
linear_mod = lm(logratio ~ range, data = train_df)

smooth_mod = mgcv::gam(logratio ~ s(range), data = train_df)

wiggly_mod = mgcv::gam(logratio ~ s(range, k = 30),  sp = 10e-6, data = train_df)
```

Look at this
```{r}
train_df |> 
  add_predictions(wiggly_mod) |> 
  ggplot(aes(x = range, y =logratio)) +
  geom_point() +
  geom_line(aes(y = pred), color = "red")
```

Try computing our RMSEs

```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## ITERATE!!
```{r}
cv_df = 
  crossv_mc(lidar_df, n = 100) |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

Did this work?

```{r}
cv_df |> 
  pull(train) |> nth(3)
```

Let's fit models over and over

```{r}
lidar_lm = function(df){
  lm(logratio ~range, data = df)
}
```

```{r}
cv_df =
  cv_df |> 
  mutate(
    linear_fits = map(train, \(df) lm(logratio ~ range, data = df)),
    smooth_fits = map(train, \(df) mgcv::gam(logratio ~ s(range), data = df)),
    wiggly_fits = map(train, \(df)mgcv::gam(logratio ~ s(range, k =50), 
                                            sp = 10e-8, data = df))
  ) |> 
  mutate(
    rmse_line = map2_dbl(linear_fits, test, rmse),
    rmse_smooth = map2_dbl(smooth_fits, test, rmse),
    rmse_wiggly = map2_dbl(wiggly_fits, test, rmse)
  )
```

Let's try to look at this better
```{r}
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) |> 
  ggplot(aes(x = model, y = rmse,fill = model)) +
  geom_violin()
```

